// Maps Webster's dictionary abbreviations (case-sensitive) to their expanded forms.
// Expansions are lowercased to match the loweredWordToWordId lookup.
const ABBREVIATIONS: Record<string, string> = {
  // Subject / field labels
  Anat:   'anatomy',
  Agric:  'agriculture',
  Alg:    'algebra',
  Antiq:  'antiquity',
  Arch:   'architecture',
  Arith:  'arithmetic',
  Astron: 'astronomy',
  Biol:   'biology',
  Bot:    'botany',
  Chem:   'chemistry',
  Com:    'commerce',
  Conch:  'conchology',
  Dyeing: 'dyeing',
  Eccl:   'ecclesiastical',
  Entom:  'entomology',
  Eth:    'ethics',
  Fort:   'fortification',
  Geog:   'geography',
  Geol:   'geology',
  Geom:   'geometry',
  Gram:   'grammar',
  Her:    'heraldry',
  Ichth:  'ichthyology',
  Illust: 'illustration',
  Log:    'logic',
  Mach:   'machinery',
  Math:   'mathematics',
  Mech:   'mechanics',
  Med:    'medicine',
  Metaph: 'metaphysics',
  Mil:    'military',
  Min:    'mineralogy',
  Mus:    'music',
  Naut:   'nautical',
  Nav:    'navigation',
  Opt:    'optics',
  Ornith: 'ornithology',
  Pharm:  'pharmacy',
  Phon:   'phonetics',
  Physiol:'physiology',
  Print:  'printing',
  Rhet:   'rhetoric',
  Surg:   'surgery',
  Theol:  'theology',
  Zo:     'zoology',
  Zool:   'zoology',

  // Usage / grammar labels
  Obs:    'obsolete',
  Colloq: 'colloquial',
  Pref:   'prefix',
  pref:   'prefix',
  adv:    'adverb',
  esp:    'especially',
  pl:     'plural',
  prob:   'probably',
  perh:   'perhaps',
  lit:    'literally',
  fig:    'figurative',
  cf:     'compare',
  Cf:     'compare',
  Bp:     'bishop',
  Dr:     'doctor',
  Eng:    'english',

  // Language / origin labels
  AS:   'anglo-saxon',
  Dan:  'danish',
  Du:   'dutch',
  fr:   'french',
  Fr:   'french',
  Gael: 'gaelic',
  Goth: 'gothic',
  Gr:   'greek',
  Heb:  'hebrew',
  Icel: 'icelandic',
  Ir:   'irish',
  It:   'italian',
  Jap:  'japanese',
  L:    'latin',
  LL:   'latin',
  LG:   'german',
  NL:   'latin',
  Nor:  'norwegian',
  OHG:  'german',
  Per:  'persian',
  Port: 'portuguese',
  Prov: 'provencal',
  Rom:  'romance',
  Russ: 'russian',
  Sax:  'saxon',
  Skr:  'sanskrit',
  Slav: 'slavonic',
  Sp:   'spanish',
  Sw:   'swedish',
  Teut: 'teutonic',
  Turk: 'turkish',
  W:    'welsh',
};

export function lookupAbbreviation(token: string, loweredWordToWordId: Map<string, string>): string | undefined {
  const expansion = ABBREVIATIONS[token];
  if (!expansion) return undefined;
  return loweredWordToWordId.get(expansion);
}
