name: Dictionary Data Upload

on:
 push:
   branches:
     - main

permissions:
  id-token: write
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_ROLE_REGION }}
        role-session-name: dictionary-parser-upload

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set short git commit SHA
      id: git
      shell: bash
      run: echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> "$GITHUB_OUTPUT"

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm ci --prefer-offline
        echo "Verifying installation..."
        npm list --depth=0

    - name: Generate dictionary data
      run: |
        echo "Node.js version: $(node -v)"
        echo "NPM version: $(npm -v)"
        echo "Starting dictionary parsing..."
        npm run parse
        echo "Dictionary parsing completed successfully"
  
    - name: Verify and compress data
      run: |
        echo "Verifying output files exist..."
        if [ ! -d "output" ] || [ -z "$(ls -A output)" ]; then
          echo "Error: output directory not found or empty"
          exit 1
        fi
        echo "Compressing JSON files..."
        for file in output/*.json; do
          if [ -f "$file" ]; then
            echo "Compressing $file..."
            jq -c . "$file" | gzip -9 > "${file}.gz"
          fi
        done
        echo "Compression completed. File sizes:"
        ls -lh output/

    - name: Version
      id: version
      shell: bash
      env:
        SHORT_SHA: ${{ steps.git.outputs.short_sha }}
      run: |
        echo "value=v$(date +%Y%m%d)-${SHORT_SHA}" >> "$GITHUB_OUTPUT"

    - name: Upload to S3
      shell: bash
      env:
        S3_BASE_URL: s3://${{ vars.S3_BUCKET }}/${{ steps.version.outputs.value }}
      run: |
        echo "Uploading output folder to S3: $S3_BASE_URL"
        if aws s3 sync output/ "$S3_BASE_URL/" --no-progress; then
          echo "✅ Upload successful"
          echo -e "### 📦 S3 Upload Successful\n\n**Location:** \`${S3_BASE_URL}/\`\n**Version:** \`${{ steps.version.outputs.value }}\`" >> "$GITHUB_STEP_SUMMARY"
        else
          echo "❌ Upload failed"
          exit 1
        fi
        
        # Verify upload
        echo "Verifying upload..."
        aws s3 ls "$S3_BASE_URL/" --human-readable --recursive
